
FROM elasticsearch:7.14.2

LABEL org.opencontainers.image.authors="admin@magenx.com"

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-phonetic
