# volatile cache — no persistence
save ""
dir /data

activerehashing yes
loglevel warning

maxmemory-policy allkeys-lru
replica-lazy-flush yes
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
lazyfree-lazy-user-del yes
