# session store — RDB + AOF
dir /data
save 900 1
save 300 10
save 60 10000
dbfilename session.rdb
rdbcompression yes

appendonly yes
appendfsync everysec
appendfilename session.aof
aof-load-truncated yes
aof-use-rdb-preamble yes
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

activerehashing yes
loglevel warning

maxmemory-policy allkeys-lru
replica-lazy-flush yes
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
lazyfree-lazy-user-del yes
